# Generated by Django 4.1 on 2023-07-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_bid_listing_highest_bidder_delete_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
