# Generated by Django 4.1 on 2023-07-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_bid_alter_listing_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='auctions.comment'),
        ),
    ]
