# Generated by Django 4.1 on 2023-07-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_comment_reply_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ANTIQUES', 'Antiques'), ('AUTOMOTIVE', 'Automotive'), ('BOOKS', 'Books/Textbooks'), ('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('TOYS', 'Toys'), ('HOME', 'Home/Kitchen')], default='Not Provided', max_length=64),
        ),
    ]
