# Generated by Django 4.1 on 2023-07-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_highest_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(default='No image provided', max_length=1000),
        ),
    ]
